language: java

sudo: required

os:
  - linux
  - osx

osx_image: xcode9.3

branches:
  only:
    - Projekt_Two_GUI

script:
  - ./gradlew clean
  - ./gradlew build
  - ./gradlew fatJar

deploy:
  provider: releases
  file_glob: true
  api_key: $token
  email: tadev3@gmail.com
  file: build/libs/*
  skip_cleanup: true
  overwrite: true
  on:
    tags: true